# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180426_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='active_status',
            field=models.BooleanField(default=0, verbose_name=b'\xe6\xbf\x80\xe6\xb4\xbb\xe7\x8a\xb6\xe6\x80\x81'),
        ),
    ]
